version: '2'
services:
  nginx:
    image: nginx
    networks:
      - default
      - web
    links:
      - php
    volumes_from:
      - php
    volumes:
      - ./nginx.conf.d:/etc/nginx/conf.d:ro
      - ./php_inc:/etc/nginx/php_inc:ro
    environment:
      - VIRTUAL_HOST=zfix.org,t.zfix.org,mongan.zfix.org,openid.zfix.org,openid.mrksr.de
      - CERT_NAME=shared

  php:
    image: mrksr/php
    volumes:
      - /srv/php:/srv

networks:
  web:
    external:
      name: nginx_default
