version: '2'
services:
  nginx:
    image: nginx
    networks:
      - default
      - web
    links:
      - php
    volumes_from:
      - php
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./php_inc:/etc/nginx/php_inc:ro
    environment:
      - VIRTUAL_HOST=rss.zfix.org,rss.mrksr.de
      - CERT_NAME=shared

  php:
    image: mrksr/tt-rss
    build: .
    networks:
      - default
      - ldap
    links:
      - database
    external_links:
      - ldap
    volumes:
      - ./config.php:/srv/config.php:ro
      - /srv/tt-rss/cache:/srv/cache
      - /srv/tt-rss/feed-icons:/srv/feed-icons
      - /srv/tt-rss/lock:/srv/lock

  daemon:
    image: mrksr/tt-rss
    build: .
    links:
      - database
    volumes_from:
      - php
    command:
      - /srv/update_daemon2.php
    user: www-data

  database:
    image: postgres
    volumes:
      - /srv/tt-rss/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

networks:
  web:
    external:
      name: nginx_default
  ldap:
    external:
      name: ldap_default
