version: '2'
services:
  mumble:
    image: mrksr/mumble
    build: .
    ports:
      - "64738:64738"
      - "64738:64738/udp"
    volumes:
      - ./mumble-server.ini:/etc/mumble-server.ini:ro
      - /srv/letsencrypt:/letsencrypt:ro
      - /srv/mumble:/var/lib/mumble-server
