version: '2'
services:
  nginx:
    image: nginx
    networks:
      - default
      - web
    links:
      - namegen
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src/frontend:/static:ro
    environment:
      - VIRTUAL_HOST=flask.zfix.org,flask.mrksr.de
      - CERT_NAME=shared

  namegen:
    image: mrksr/namegen
    build: .
    volumes:
      - ./src/backend:/src
      - ./uwsgi.ini:/etc/uwsgi/uwsgi.ini

networks:
  web:
    external:
      name: nginx_default
