version: '3'

services:
  db:
    image: postgres:alpine
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - db.env

  app:
    build: ./nextcloud-cron
    restart: always
    volumes:
      - nextcloud:/var/www/html
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=nextcloud
    env_file:
      - db.env
    depends_on:
      - db
    external_links:
      - ldap
    networks:
      - default
      - ldap

  web:
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - nextcloud:/var/www/html:ro
    environment:
      - VIRTUAL_HOST=cloud.zfix.org,cloud.mrksr.de
      - CERT_NAME=shared
    depends_on:
      - app
    networks:
      - default
      - web

volumes:
  db:
  nextcloud:

networks:
  web:
    external:
      name: nginx_default
  ldap:
    external:
      name: ldap_default
