version: '2'
services:
  nginx:
    image: nginx
    networks:
      - default
      - web
    links:
      - gitea
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - VIRTUAL_HOST=git.zfix.org,git.mrksr.de

  gitea:
    image: gitea/gitea
    networks:
      - default
      - ldap
    ports:
      - "2222:22"
    links:
      - database
    external_links:
      - ldap
    volumes:
      - ./lib/gitea:/data/gitea
      - ./lib/git:/data/git

  database:
    image: postgres
    volumes:
      # FIXME: Proper lib path
      - ./lib/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

networks:
  web:
    external:
      name: nginx_default
  ldap:
    external:
      name: ldap_default
