version: '2'
services:
  nginx_fileserver:
    image: nginx
    networks:
      - default
      - web
    volumes:
      - ./nginx_fileserver.conf:/etc/nginx/conf.d/default.conf:ro
      - ./stdauth_private:/etc/nginx/stdauth_private:ro
    volumes_from:
      - syncthing:ro
    environment:
      - VIRTUAL_HOST=m.zfix.org,m.mrksr.de,b.zfix.org,b.mrksr.de,btsync.zfix.org,btsync.mrksr.de,s.zfix.org,s.mrksr.de
      - CERT_NAME=shared

  syncthing:
    image: mrksr/syncthing
    build: .
    networks:
      - default
      - web
    ports:
      - 22000:22000
      - 21027:21027/udp
    volumes:
      - /srv/syncthing/config:/syncthing/config
      - /srv/syncthing/data:/syncthing/data
    environment:
      - VIRTUAL_HOST=syncthing.zfix.org,syncthing.mrksr.de
      - VIRTUAL_PORT=8384
      - CERT_NAME=shared

networks:
  web:
    external:
      name: nginx_default
