version: '2'
services:
  nginx:
    image: nginx
    networks:
      - default
      - web
    links:
      - radicale
      - ldap_auth
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - VIRTUAL_HOST=radicale.zfix.org,radicale.mrksr.de,dav.zfix.org,dav.mrksr.de
      - CERT_NAME=shared

  ldap_auth:
    image: mrksr/nginx-ldap-auth
    build: nginx-ldap-auth
    ports:
      - "8888:8888"
    networks:
      - default
      - ldap
    external_links:
      - ldap

  radicale:
    image: mrksr/radicale
    build: .
    volumes:
      - ./radicale.wsgi:/src/radicale.wsgi:ro
      - ./radicale:/etc/radicale:ro
      - ./uwsgi.ini:/etc/uwsgi/uwsgi.ini:ro
      - /srv/webdav:/var/lib/radicale/collections

networks:
  web:
    external:
      name: nginx_default
  ldap:
    external:
      name: ldap_default
