version: '2'
services:
  nginx:
    image: nginx
    networks:
      - default
      - web
    links:
      - radicale
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./radicale/users:/etc/radicale/users:ro
    environment:
      - VIRTUAL_HOST=radicale.zfix.org,radicale.mrksr.de,dav.zfix.org,dav.mrksr.de
      - CERT_NAME=shared

  radicale:
    image: mrksr/radicale
    build: .
    volumes:
      - ./radicale.wsgi:/src/radicale.wsgi:ro
      - ./radicale:/etc/radicale:ro
      - ./uwsgi.ini:/etc/uwsgi/uwsgi.ini:ro
      - /srv/webdav:/radicale

networks:
  web:
    external:
      name: nginx_default
