version: '3'

volumes:
  portainer_data: {}

services:
  portainer:
    image: portainer/portainer
    restart: always
    command:
      # - "--templates=http://templates/templates.json"
      - "--host=unix:///var/run/docker.sock"
    networks:
      - default
      - ldap
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  nginx:
    image: nginx
    networks:
      - default
      - web
    links:
      - portainer
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - VIRTUAL_HOST=status.zfix.org,status.mrksr.de
      - CERT_NAME=shared

networks:
  web:
    external:
      name: nginx_default
  ldap:
    external:
      name: ldap_default
