version: '2'
services:
  prosody:
    image: mrksr/prosody
    build: .
    ports:
      - 5222:5222
      - 5269:5269
      - 5280:5280
    volumes:
      - ./prosody.cfg.lua:/etc/prosody/prosody.cfg.lua
      - ./zfix.org.cfg.lua:/etc/prosody/zfix.org.cfg.lua
      - ./dhparam.pem:/etc/prosody/dhparam.pem
    links:
      - database

  database:
    image: postgres
    volumes:
      # FIXME: Proper lib path
      - ./lib:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=prosody
      - POSTGRES_PASSWORD=prosody
