version: '2'
services:
  prosody:
    image: mrksr/prosody
    build: .
    networks:
      - default
      - ldap
    ports:
      - 5222:5222
      - 5269:5269
      - 5280:5280
      - 5281:5281
      - 3478:3478/udp
    volumes:
      - ./prosody.cfg.lua:/etc/prosody/prosody.cfg.lua:ro
      - ./zfix.org.cfg.lua:/etc/prosody/zfix.org.cfg.lua:ro
      - ./dhparam.pem:/etc/prosody/dhparam.pem:ro
      - /srv/letsencrypt:/letsencrypt:ro
    links:
      - database
    external_links:
      - ldap

  database:
    image: postgres
    volumes:
      - /srv/prosody/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

networks:
  ldap:
    external:
      name: ldap_default
