version: '2'
services:
  mail:
    image: mrksr/mail
    container_name: mail
    build: .
    networks:
      - default
      - ldap
      - web
    ports:
      - "25:25"
      - "110:110"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
      - "995:995"
      - "4190:4190"
      - "11334"
    volumes:
      # state
      - /srv/mail/mail:/vmail
      - /srv/mail/sieve.global.d:/sieve.global.d
      - /srv/mail/dkim:/dkim:ro
      - /srv/letsencrypt:/letsencrypt:ro
      - /etc/localtime:/etc/localtime:ro

      # programs
      - ./supervisord.conf:/etc/supervisor/supervisord.conf:ro
      - ./rsyslog.conf:/etc/rsyslog.conf:ro
      - ./rsyslog.d/00-stdout.conf:/etc/rsyslog.d/00-stdout.conf:ro

      - ./dovecot:/etc/dovecot:ro

      # We need to specify single files for postfix to keep the dynamicmaps.cf which is part of the container.
      - ./postfix-wrapper.sh:/usr/sbin/postfix-wrapper.sh:ro
      - ./postfix/main.cf:/etc/postfix/main.cf:ro
      - ./postfix/master.cf:/etc/postfix/master.cf:ro
      - ./postfix/ldap:/etc/postfix/ldap:ro
      - ./postfix/dhparam2048.pem:/etc/postfix/dhparam2048.pem:ro

      - /srv/mail/rspamd:/var/lib/rspamd
      - ./rspamd/local.d:/etc/rspamd/local.d:ro
      - ./rspamd/override.d:/etc/rspamd/override.d:ro
    links:
      - redis
    external_links:
      - ldap
    environment:
      - VIRTUAL_HOST=rspamd.zfix.org,rspamd.mrksr.de
      - VIRTUAL_PORT=11334
      - CERT_NAME=shared

  redis:
    image: redis
    volumes:
      - /srv/mail/redis:/data

networks:
  web:
    external:
      name: nginx_default
  ldap:
    external:
      name: ldap_default
