version: '2'
services:
  nginx:
    image: nginx
    networks:
      - default
      - web
    links:
      - hg
      - tutor
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src/static:/static:ro
    environment:
      - VIRTUAL_HOST=hg.zfix.org,tutor.zfix.org,info2.zfix.org,theo.zfix.org,ds.zfix.org,hg.mrksr.de,tutor.mrksr.de,info2.mrksr.de,theo.mrksr.de,ds.mrksr.de
      - CERT_NAME=shared

  hg:
    image: mrksr/hgweb
    build: .
    volumes:
      - ./src/hgweb:/src:ro
      - ./uwsgi_hg.ini:/etc/uwsgi/uwsgi.ini:ro
      - /srv/hg:/hg:ro

  tutor:
    image: mrksr/hgweb
    build: .
    volumes:
      - ./src/hgweb:/src:ro
      - ./uwsgi_tutor.ini:/etc/uwsgi/uwsgi.ini:ro
      - /srv/hg:/hg:ro

networks:
  web:
    external:
      name: nginx_default
