version: '2.1'

services:
  webserver:
    image: danielquinn/paperless
    networks:
      - default
      - web
    # uncomment the following line to start automatically on system boot
    # restart: always
    # ports:
      # You can adapt the port you want Paperless to listen on by
      # modifying the part before the `:`.
      # - "8000:8000"
    expose:
      - "8000"
    healthcheck:
      test: ["CMD", "curl" , "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /srv/paperless/data:/usr/src/paperless/data
      - /srv/paperless/media:/usr/src/paperless/media
    env_file:
      - docker-compose.env
      - docker-compose.secret.env
    # The reason the line is here is so that the webserver that doesn't do
    # any text recognition and doesn't have to install unnecessary
    # languages the user might have set in the env-file by overwriting the
    # value with nothing.
    environment:
      - PAPERLESS_OCR_LANGUAGES=
      - VIRTUAL_HOST=paperless.zfix.org,paperless.mrksr.de
      # - VIRTUAL_PORT=8000
      - CERT_NAME=shared
    command: ["runserver", "--insecure", "--noreload", "0.0.0.0:8000"]

  consumer:
    image: danielquinn/paperless
    # uncomment the following line to start automatically on system boot
    # restart: always
    depends_on:
      - webserver
      # webserver:
        # condition: service_healthy
    volumes:
      - /srv/paperless/data:/usr/src/paperless/data
      - /srv/paperless/media:/usr/src/paperless/media
      # You have to adapt the local path you want the consumption
      # directory to mount to by modifying the part before the ':'.
      - /srv/syncthing/data/paperless/consume:/consume
      # Likewise, you can add a local path to mount a directory for
      # exporting. This is not strictly needed for paperless to
      # function, only if you're exporting your files: uncomment
      # it and fill in a local path if you know you're going to
      # want to export your documents.
      - /srv/syncthing/data/paperless/export:/export
    env_file:
      - docker-compose.env
      - docker-compose.secret.env
    command: ["document_consumer"]

networks:
  web:
    external:
      name: nginx_default
