version: '2'

services:
  postgresql:
    restart: always
    env_file:
      - production.env
      - production_secret.env

  redis:
    restart: always

  rabbitmq:
    restart: always
    env_file:
      - production.env
      - production_secret.env

  backend:
    restart: always
    env_file:
      - production.env
      - production_secret.env
    environment:
      - TAIGA_DEBUG=false
      - DJANGO_DEBUG=false
    command: ['gunicorn', '--workers', '4', '-b', '0.0.0.0:8000', 'taiga.wsgi' ]

  frontend:
    restart: always
    networks:
      - default
      - web
    env_file:
      - production.env
      - production_secret.env
    environment:
      - TAIGA_DEBUG=false
      - VIRTUAL_HOST=taiga.zfix.org,taiga.mrksr.de
      - CERT_NAME=shared

  celeryworker:
    restart: always
    env_file:
      - production.env
      - production_secret.env
    environment: []
    # Maybe you want to increase the workers, see <celeryworker> in docker-compose.yml
    command: ['celery', '-A', 'taiga', 'worker', '-c', '4', '--loglevel', 'info' ]

  events:
    restart: always
    env_file:
      - production.env
      - production_secret.env

networks:
  web:
    external:
      name: nginx_default
