version: '3'

volumes:
  postgres_data: {}
  synapse_data: {}
  whatsapp_data: {}

services:
  synapse:
    image: docker.io/matrixdotorg/synapse:latest
    container_name: matrix
    networks:
      - default
      - ldap
    # Since synapse does not retry to connect to the database, restart
    # upon failure
    restart: unless-stopped
    environment:
      - UID=0
      - SYNAPSE_SERVER_NAME=zfix.org
      - SYNAPSE_REPORT_STATS=no
    volumes:
      - synapse_data:/data
      - whatsapp_data:/bridges/whatsapp:ro
      # NOTE(mrksr): We overwrite the jinja templates used by the synapse
      # docker file with our own configuration. Thus, most of the variables in
      # the original documentation are ignored.
      - ./homeserver.yaml:/conf/homeserver.yaml:ro
      - ./log_config.yaml:/conf/log_config.yaml:ro
      - /srv/letsencrypt:/letsencrypt:ro
    depends_on:
      - db
    ports:
      - 8448:8448/tcp
    external_links:
      - ldap

  riot:
    image: bubuntux/riot-web:latest
    networks:
      # - default # NOTE(mrksr): No need to interact with anything server-side
      - web
    volumes:
      - ./riot_config.json:/etc/riot-web/config.json:ro
    environment:
      - VIRTUAL_HOST=riot.zfix.org,riot.mrksr.de
      - CERT_NAME=shared

  nginx:
    image: nginx
    networks:
      - default
      - web
    links:
      - synapse
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - VIRTUAL_HOST=matrix.zfix.org,matrix.mrksr.de
      - CERT_NAME=shared

  db:
    image: docker.io/postgres:10-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  whatsapp:
    image: dock.mau.dev/tulir/mautrix-whatsapp
    links:
      - synapse
    volumes:
      - whatsapp_data:/data
      - ./whatsapp_config.yaml:/mrksr/config.yaml:ro
      - ./healthcheck.sh:/mrksr/healthcheck.sh:ro
    restart: always
    entrypoint:
      # NOTE(mrksr): The bridge wants to write and chown the settings files. To
      # keep them read-only on the outside we copy them to the volume.
      - sh
      - -c
      - 'cp /mrksr/* /data; exec /docker-run.sh'
    # healthcheck:
    #   test: ["CMD-SHELL", "/mrksr/healthcheck.sh"]
    #   interval: 20h
    #   timeout: 10s
    #   retries: 1

networks:
  web:
    external:
      name: nginx_default
  ldap:
    external:
      name: ldap_default
