version: "3"

volumes:
  postgres_data: {}
  synapse_data: {}
  slidingsync_postgres_data: {}
  whatsapp_data: {}
  signal_bridge_data: {}
  signal_postgres_data: {}

services:
  synapse:
    image: docker.io/matrixdotorg/synapse:latest
    container_name: matrix
    networks:
      - default
      - ldap
    restart: unless-stopped
    environment:
      - UID=0
      - SYNAPSE_SERVER_NAME=zfix.org
      - SYNAPSE_REPORT_STATS=no
    volumes:
      - synapse_data:/data
      - whatsapp_data:/bridges/whatsapp:ro
      - signal_bridge_data:/bridges/signal:ro
      - /srv/letsencrypt:/letsencrypt:ro
    links:
      - postgres
    depends_on:
      - postgres
    ports:
      - 8448:8448/tcp
    external_links:
      - ldap

  slidingsync:
    image: ghcr.io/matrix-org/sliding-sync:latest
    networks:
      - default
    restart: unless-stopped
    depends_on:
      - slidingsync_postgres
    env_file:
      - path: ./slidingsync_secret.env
        required: true
    environment:
      # - "SYNCV3_SECRET=some_secret" # NOTE(mrksr): In the .env file!
      - "SYNCV3_SERVER=https://zfix.org"
      - "SYNCV3_DB=user=postgres dbname=postgres sslmode=disable host=slidingsync_postgres password=postgres"
      - "SYNCV3_BINDADDR=0.0.0.0:8881"

  slidingsync_postgres:
    image: docker.io/postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - slidingsync_postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx
    restart: unless-stopped
    container_name: matrix_nginx
    networks:
      - default
      - web
    links:
      - synapse
      - slidingsync
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

  postgres:
    image: docker.io/postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  whatsapp:
    image: dock.mau.dev/mautrix/whatsapp
    restart: unless-stopped
    links:
      - synapse
    volumes:
      - whatsapp_data:/data

  signal:
    image: dock.mau.dev/mautrix/signal
    restart: unless-stopped
    links:
      - synapse
      - signal_postgres
    volumes:
      - signal_bridge_data:/data

  signal_postgres:
    image: postgres:13-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DATABASE: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - signal_postgres_data:/var/lib/postgresql/data

networks:
  web:
    external:
      name: nginx_default
  ldap:
    external:
      name: ldap_default
