version: "3"

volumes:
  postgres_data: {}
  synapse_data: {}
  whatsapp_data: {}
  signal_bridge_data: {}
  signal_signald_data: {}
  signal_postgres_data: {}

services:
  synapse:
    image: docker.io/matrixdotorg/synapse:latest
    container_name: matrix
    networks:
      - default
      - ldap
    # Since synapse does not retry to connect to the database, restart
    # upon failure
    restart: unless-stopped
    environment:
      - UID=0
      - SYNAPSE_SERVER_NAME=zfix.org
      - SYNAPSE_REPORT_STATS=no
    volumes:
      - synapse_data:/data
      - whatsapp_data:/bridges/whatsapp:ro
      - signal_bridge_data:/bridges/signal:ro
      # NOTE(mrksr): We overwrite the jinja templates used by the synapse
      # docker file with our own configuration. Thus, most of the variables in
      # the original documentation are ignored.
      # NOTE(mrksr): Synapse no longer has an on-the-fly config mode. There is
      # still a migrate_config command though (see official README) to generate
      # secretes based on our config. For now we use this.
      - ./homeserver.yaml:/conf/homeserver.yaml:ro
      - ./log_config.yaml:/conf/log_config.yaml:ro
      - /srv/letsencrypt:/letsencrypt:ro
    links:
      - postgres
    depends_on:
      - postgres
    ports:
      - 8448:8448/tcp
    external_links:
      - ldap

  nginx:
    image: nginx
    networks:
      - default
      - web
    links:
      - synapse
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - VIRTUAL_HOST=matrix.zfix.org,matrix.mrksr.de
      - CERT_NAME=shared

  postgres:
    image: docker.io/postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  whatsapp:
    image: dock.mau.dev/mautrix/whatsapp
    restart: unless-stopped
    links:
      - synapse
    volumes:
      - whatsapp_data:/data

  signal:
    image: dock.mau.dev/mautrix/signal
    restart: unless-stopped
    links:
      - synapse
      - signald
      - signal_postgres
    volumes:
      - signal_bridge_data:/data
      - signal_signald_data:/signald
    depends_on:
      - signald

  signald:
    container_name: signald
    image: docker.io/signald/signald
    restart: unless-stopped
    volumes:
      - signal_signald_data:/signald

  signal_postgres:
    image: postgres:13-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DATABASE: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - signal_postgres_data:/var/lib/postgresql/data

networks:
  web:
    external:
      name: nginx_default
  ldap:
    external:
      name: ldap_default
