version: '2'
services:
  nginx:
    image: nginx
    networks:
      - default
      - web
    links:
      - php
    volumes_from:
      - php
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./php_inc:/etc/nginx/php_inc:ro
    environment:
      - VIRTUAL_HOST=hassprophet.de,www.hassprophet.de,hassprophet.zfix.org,www.hassprophet.zfix.org,hassprophet.mrksr.de,www.hassprophet.zfix.org
      - CERT_NAME=shared

  php:
    image: mrksr/php-5
    links:
      - database
    volumes:
      - /srv/hassprophet/www:/srv

  database:
    image: mariadb
    volumes:
      - /srv/hassprophet/mariadb:/var/lib/mysql
      - ./hassprophet.sql:/docker-entrypoint-initdb.d/hassprophet.sql:ro
    environment:
      - MYSQL_ROOT_PASSWORD=stellarlyunbreakablekey
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_DATABASE=mysql

networks:
  web:
    external:
      name: nginx_default
